"""Summarise a generated world: counts per pattern, per category and per area.

    python -m jachai.world.summary [data/world] [--out reports/world_summary.md]

Reads the parquet files written by `make world`, prints a Markdown report and
writes it to reports/ so every number we quote comes from code.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import pandas as pd

from jachai.world.config import REPO_ROOT
from jachai.world.generate import read_world_tables
from jachai.world.world import TRUE_LABEL, TRUE_PATTERN


def md_table(df: pd.DataFrame) -> str:
    """Minimal Markdown table (avoids an extra dependency)."""
    df = df.reset_index()
    cols = [str(c) for c in df.columns]

    def fmt(v) -> str:
        if isinstance(v, float):
            return f"{v:,.3f}" if abs(v) < 1 else f"{v:,.0f}"
        if isinstance(v, int):
            return f"{v:,}"
        return str(v)

    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    lines += ["| " + " | ".join(fmt(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join(lines)


def by_pattern(t: dict[str, pd.DataFrame]) -> pd.DataFrame:
    qr, shops, p2p = t["qr_payments"], t["shops"], t["p2p_transfers"]
    # Every pattern seen anywhere gets a row, even with no QR payments (p2p_disguise).
    labelled = pd.concat([df[[TRUE_PATTERN, TRUE_LABEL]] for df in (qr, shops, p2p)])
    out = labelled.groupby(TRUE_PATTERN)[TRUE_LABEL].max().to_frame("label")
    grouped = qr.groupby(TRUE_PATTERN)["amount"]
    out["qr_payments"] = grouped.size()
    out["qr_taka"] = grouped.sum()
    out["median_ticket"] = grouped.median()
    out["shops"] = shops[TRUE_PATTERN].value_counts()
    out["customers"] = t["customers"][TRUE_PATTERN].value_counts()
    for table in ("p2p_transfers", "remittances", "add_money"):
        out[table] = t[table][TRUE_PATTERN].value_counts()
    out = out.fillna(0).astype("int64").sort_values(["label", "qr_taka"], ascending=False)
    return out.rename_axis("pattern")


def by_category(t: dict[str, pd.DataFrame]) -> pd.DataFrame:
    qr, shops = t["qr_payments"], t["shops"]
    qr = qr.assign(category=qr["shop_id"].map(shops.set_index("shop_id")["category"]))
    out = shops.groupby("category").agg(shops=("shop_id", "size"), misuse_shops=(TRUE_LABEL, "sum"))
    out["qr_payments"] = qr.groupby("category").size()
    out["median_ticket"] = qr.groupby("category")["amount"].median()
    out["misuse_payment_share"] = qr.groupby("category")[TRUE_LABEL].mean()
    return out


def by_area(t: dict[str, pd.DataFrame]) -> pd.DataFrame:
    shops = t["shops"]
    return shops.groupby("area_type").agg(
        shops=("shop_id", "size"),
        misuse_shops=(TRUE_LABEL, "sum"),
        misuse_share=(TRUE_LABEL, "mean"),
    )


def cases_table(t: dict[str, pd.DataFrame]) -> pd.DataFrame:
    """Past cases by source: how many, how many closed, how many verdicts are right."""
    cases = t["cases"].merge(t["shops"][["shop_id", TRUE_LABEL]], on="shop_id")
    cases = cases.assign(
        closed=cases["closed_on"].notna(),
        right=cases["verdict"] == cases[TRUE_LABEL],
        misuse_shop=cases[TRUE_LABEL] == 1,
    )
    out = cases.groupby("source").agg(
        cases=("case_id", "size"),
        closed=("closed", "sum"),
        misuse_shops=("misuse_shop", "sum"),
        verdict_right=("right", "sum"),
    )
    out.loc["all"] = out.sum()
    out["share_of_shops"] = out["cases"] / len(t["shops"])
    return out


def render(world_dir: Path) -> str:
    t = read_world_tables(world_dir)
    manifest = json.loads((world_dir / "manifest.json").read_text(encoding="utf-8"))
    rows = pd.DataFrame({"rows": manifest["rows"]}).rename_axis("table")
    qr = t["qr_payments"]
    misuse_value = qr.loc[qr[TRUE_LABEL] == 1, "amount"].sum() / qr["amount"].sum()
    return (
        "\n\n".join(
            [
                "# Synthetic world summary",
                "Generated by `make world` (`python -m jachai.world.summary`). Synthetic data "
                "only; these counts describe the generator, not real upay traffic.",
                f"- Seed: {manifest['seed']}\n"
                f"- Config fingerprint: `{manifest['config_fingerprint']}`\n"
                f"- Window: {manifest['window'][0]} to {manifest['window'][1]}\n"
                f"- P2P what-if scenario: {'on' if manifest['p2p_qr_enabled'] else 'off'}\n"
                f"- Misuse share of QR payments: {qr[TRUE_LABEL].mean():.2%} by count, "
                f"{misuse_value:.2%} by value",
                "## Rows per table",
                md_table(rows),
                "## Per pattern\n\n`label` 1 = misuse, 0 = honest (normal or hard negative). "
                "Shop and customer columns count those tagged with the pattern.",
                md_table(by_pattern(t)),
                "## Per category",
                md_table(by_category(t)),
                "## Per area type",
                md_table(by_area(t)),
                "## Past cases (observable, shop-level) vs hidden truth",
                md_table(cases_table(t)),
            ]
        )
        + "\n"
    )


def default_world_dir() -> Path:
    return REPO_ROOT / os.environ.get("JACHAI_DATA_DIR", "data") / "world"


def default_report_path() -> Path:
    return REPO_ROOT / os.environ.get("JACHAI_REPORTS_DIR", "reports") / "world_summary.md"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("world_dir", nargs="?", type=Path, default=default_world_dir())
    parser.add_argument("--out", type=Path, default=default_report_path())
    args = parser.parse_args(argv)
    text = render(args.world_dir)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(text)
    print(f"Written to {args.out}")


if __name__ == "__main__":
    main()
