"""`python -m jachai.simulate` (what `make sim` / `make sim-fast` run).

    python -m jachai.simulate [--set analyst_capacity_per_day=10 --set limit_level=50000]

Loads the trained system from MODEL_DIR (run `make train` / `make train-fast`
first), builds or loads the cached replay inputs, runs policies A-E and writes
reports/<profile>/simulator/results.json and results.md.
"""

from __future__ import annotations

import argparse
import json

import pandas as pd
import yaml

from jachai.features.config import load_thresholds
from jachai.labels.config import load_rules
from jachai.models.config import load_models_config
from jachai.simulate.config import load_simulator_config
from jachai.simulate.inputs import build_inputs, cached_inputs
from jachai.simulate.policies import run_all
from jachai.system import load_system
from jachai.world.config import REPO_ROOT, load_world_config, profile_path
from jachai.world.summary import default_model_dir, default_report_path, md_table

COLUMNS = {
    "misuse_taka_stopped": "misuse Tk stopped",
    "misuse_taka_rerouted": "misuse Tk rerouted to agents",
    "misuse_taka_still_flowing": "misuse Tk still flowing",
    "fees_recaptured": "fees recaptured Tk",
    "honest_shops_restricted": "honest shops restricted",
    "blocked_genuine_sales": "genuine sales blocked Tk",
    "analyst_alerts_per_day": "alerts per day",
    "agent_leads": "agent leads",
    "agents_signed": "agents signed",
    "genuine_commerce_share": "genuine-commerce share",
}


def parse_overrides(pairs: list[str]) -> dict:
    out = {}
    for pair in pairs:
        key, _, value = pair.partition("=")
        out[key.strip()] = yaml.safe_load(value)
    return out


def render(results: list[dict], params: dict, replay: dict) -> str:
    table = pd.DataFrame(results).set_index("name")[list(COLUMNS)].rename(columns=COLUMNS)
    total = results[0]["misuse_taka_total"]
    return (
        "\n\n".join(
            [
                "# Policy simulator",
                "Generated by `make sim` (`python -m jachai.simulate`). Synthetic data only: "
                "a separate replay world scored by the trained system (not the test set), "
                f"replay seed {replay['seed']}, last {results[0]['days']} days. Misuse taka in "
                f"the month: {total:,.0f}. Outcomes use the replay world's hidden truth.",
                md_table(table.round(3).rename_axis("policy")),
                "Parameters: " + ", ".join(f"`{k}={v}`" for k, v in params.items()),
                "A blanket limit blocks honest big sellers and misses misuse below the cap; "
                "targeted review (C, D) depends on what the alert ranks first; E turns confirmed "
                "high-demand cash-out points into licensed agents. These figures show the "
                "method on synthetic data, not expected real-world amounts.",
            ]
        )
        + "\n"
    )


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Replay one month under policies A-E.")
    parser.add_argument(
        "--set", action="append", default=[], help="override, e.g. limit_level=50000"
    )
    args = parser.parse_args(argv)

    cfg, thr, rules, models = (
        load_world_config(),
        load_thresholds(),
        load_rules(),
        load_models_config(),
    )
    sim = load_simulator_config()
    params = sim.params.with_overrides(parse_overrides(args.set))
    system = load_system(default_model_dir(), models)

    key = {
        "system": system.payment.fingerprint(),
        "replay_seed": sim.replay.seed,
        "replay_days": sim.replay.days,
        "fee_rate": cfg.regulation.agent_cash_out_fee_rate,
    }
    cache = REPO_ROOT / profile_path("data_dir", "data") / "simulator"
    inputs = cached_inputs(cache, key, lambda: build_inputs(system, cfg, thr, rules, models, sim))
    results = run_all(inputs, params)

    out = default_report_path().parent / "simulator"
    out.mkdir(parents=True, exist_ok=True)
    payload = {"replay": sim.replay.model_dump(), "params": params.model_dump(), "results": results}
    (out / "results.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    text = render(results, params.model_dump(), sim.replay.model_dump())
    (out / "results.md").write_text(text, encoding="utf-8")
    print(text)
    print(f"Written to {out}")


if __name__ == "__main__":
    main()
